### ISSUE TITLE
docker 安装教程

### ISSUE THREAD

**Issue by jqtmviyu** [zybieku/yapi#20]
下载 `fjc0k/docker-YApi` 项目的docker镜像, 用该项目的`client`和`server`替换掉容器里的 `/yapi/vendors/client`, `/yapi/vendors/server`, 可以正常启动. 

用docker的原因是因为换了arm64的服务器, npm安装依赖完全安不上 😭 

如果是迁移服务器的可以参考:

```yaml
services:
  yapi-web:
    image: jayfong/yapi:1.10.2
    container_name: yapi-web
    ports:
      - 40001:3000
    volumes:
      - ./vendors/server:/yapi/vendors/server
      - ./vendors/client:/yapi/vendors/client
    environment:
      - YAPI_ADMIN_ACCOUNT=xxx
      - YAPI_ADMIN_PASSWORD=xxx
      - YAPI_CLOSE_REGISTER=true
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_DB_USER=xxx
      - YAPI_DB_PASS=xxx
      - YAPI_DB_AUTH_SOURCE=admin
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:4.4.9
    container_name: yapi-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxx
      MONGO_INITDB_ROOT_PASSWORD: xxx
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    command: [--auth]
    restart: unless-stopped
```
